default: &default
  adapter: postgresql
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  port: <%= ENV.fetch('POSTGRES_PORT', 5432) %>
  username: <%= ENV.fetch('POSTGRES_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', '') %>
  pool: <%= ENV.fetch('POSTGRES_POOL', 5) %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DATABASE', 'lightning_talks_developemnt') %>

test:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DATABASE', 'lightning_talks_test') %>

staging:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DATABASE', 'lightning_talks_staging') %>

production:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DATABASE', 'lightning_talks_production') %>
