# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Your github client id and secret are used for Github authentication. To enable oauth on development you will need to register a new oauth application on Github. See https://developer.github.com/apps/building-integrations/setting-up-and-registering-oauth-apps/registering-oauth-apps/ for instructions.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a5b068923f5ae30cbe0e972b523e7f8da50e9f75b50bf4bbdf27adc79256f2fe58dbc72a3a502680809e05873910b65a58d160a584d809d2e8fec5e022f7e3c
  github_client_id: '********'
  github_client_secret: '********'

test:
  secret_key_base: 89133daae97f3ab1d5c31a578bfeb9fab1a3fcb657e028221b080882771734aed5b443703a65937f24aa5f6e8c7080a860bc8252a3d097def2f4f55d50dd9440

# Do not keep production secrets in the repository,
# instead read values from the environment.
staging:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  github_client_id: <%= ENV['GIHUB_AUTH_ID'] %>
  github_client_secret: <%= ENV['GIHUB_AUTH_KEY'] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  github_client_id: <%= ENV['GIHUB_AUTH_ID'] %>
  github_client_secret: <%= ENV['GIHUB_AUTH_KEY'] %>
